name: Forecast text
on:
  schedule:
    - cron: '30 11 * * *'
    - cron: '30 19 * * *'
jobs:

  bot:
    name: bot sheduled forecast
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      
      - name: Set up Python 3.10.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.9
          
      - name: Install pipenv
        run: pip install pipenv
        
      - name: Run forecast for Illes Balears
        run: |
          pipenv install
          pipenv run python src/main.py
        env:
          AEMET_API_KEY: ${{ secrets.AEMET_API_KEY }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          MAR_FORECAST_COASTAL_CHAT_ID: -1001412714734
          MAR_FORECAST_COASTAL_CODE: ILLES_BALEARS